CREATE TABLE IF NOT EXISTS prodratings (
    id BIGSERIAL PRIMARY KEY,
    prodid BIGINT REFERENCES product(id),
    rating INTEGER NOT NULL,
    addeddate TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);